config/routes.rb
Rails.application.routes.draw do
  resources :codes, only: %i(new show create) do
    resources :lines, only: [] do
      resources :comments, only: %i(new destroy create)
    end
  end

  root 'codes#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
  DURATION = {
    '1day' => 1.day,
    '1week' => 1.week,
    '1month' => 1.month,
    '1year' => 1.year,
  }

  belongs_to :syntax

  has_many :comments, inverse_of: :code

  before_validation :set_data, on: :create
  before_save :set_formatted_code

  attribute :expires, :string

  with_options presence: true do
    validates :permalink, uniqueness: true
    validates :code
    validates :expired_at
    validates :expires
  end

  def to_param
    permalink
  end

  def get_comments
    comments.order(:created_at).group_by(&:line)
  end

  def self.active(permalink)
    self.where('expired_at > NOW()').find_by_permalink!(permalink)
  end

  private

  def set_formatted_code
    self.formatted_code = CodeRay.scan(code, syntax.lang).html(css: :class)
  end

  def set_data
    self.permalink = Digest::SHA256.hexdigest("#{code}#{SecureRandom.hex(50)}").to_i(16).to_s(36)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :code, inverse_of: :comments

  with_options presence: true do
    validates :comment, allow_blank: false
    validates :line
  end
end

app/models/syntax.rb
# frozen_string_literal: true

class Syntax < ApplicationRecord
  has_many :codes

  validates :name, presence: true, uniqueness: true
  validates :lang, presence: true, uniqueness: true

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: :show

  def show

  end

  def new
    @code = Code.new
  end

  def create
    @code = Code.new(code_params)
    set_expires

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render :show, status: :created, location: @code }
      else
        format.html { render :new }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_expires
    @code.expired_at = DateTime.now + Code::DURATION[code_params[:expires]]
  end

  def set_code
    @code = Code.active params[:id]
  end

  def code_params
    params.require(:code).permit(:title, :author, :code, :syntax_id, :expires)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_code, only: %i(new create)

  def new
    @comment = @code.comments.new
  end

  def create
    @comment = @code.comments.new(comments_params)
    @comment.line = params[:line_id]

    respond_to do |format|
      if @comment.save
        format.html { redirect_to code_path @code, anchor: "l#{params[:line_id]}" }
        format.json { render :show, status: :created, location: @comment.code }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_code
    @code = Code.active params[:code_id]
  end

  def comments_params
    params.require(:comment).permit(:comment, :author, :line_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
  def expired_at
    diff = (@code.expired_at - Time.now)
    if diff < 5.minute
      'badge badge-danger'
    elsif 1.hour > diff && diff > 5.minute
      'badge badge-warning'
    else
      'badge badge-success'
    end
  end

  def get_forrmat(size, value)
    format("%#{size.to_s.size}d", value)
  end
end

app/views/codes/_form.html.slim
.form-group
  = form_for @code do |f|
    - if @code.errors.any?
        .alert.alert-danger role="alert"
          button type="button" class="close" data-dismiss="alert" aria-label="Close"
            span aria-hidden="true" &times;
          h5 = "#{pluralize(@code.errors.count, "error")} prohibited this code from being saved:"
          ul
            - @code.errors.full_messages.each do |message|
              li = message
    .row
      .col-4
        .field
          .form-group
            = f.label :title
            = f.text_field :title, class: "form-control form-control-sm"
        .field
          .form-group
            = f.label :author
            = f.text_field :author, class: "form-control form-control-sm"

      .col-4
        .field
          .form-group
            = f.label :syntax_id
            = f.collection_select :syntax_id, Syntax.all, :id, :name, {prompt: true}, class: "form-control form-control-sm"
        .field
          .form-group
            = f.label :expires
            = f.select :expires, Code::DURATION.keys, {}, class: "form-control form-control-sm"

    .field
      .form-group
        = f.label :code
        = f.text_area :code, cols: 60, rows: 15, class: "form-control"

    = f.button 'Create link', class: "btn btn-dark btn-sm"

app/views/codes/_formatted_code.slim
- lines = @code.formatted_code.lines
- comments = @code.get_comments

.CodeRay
  - lines.each.with_index do |line, i|
    - index = i + 1
    pre
      = link_to get_forrmat(lines.size, index),
        new_code_line_comment_path(@code, index, anchor: "l#{index}"), id: "l#{index}"

      | &nbsp;
      = line.html_safe
      - if comments[index]
        - comments[index].each do |comment|
          - next if comment.new_record?
          .col-9
            .row-7
              .card
                .card-body
                  span.badge.badge-secondary = l comment[:created_at], format: :short
                  | &nbsp
                  span.badge.badge-info = comment[:author]
                  p = comment[:comment]

    - if @comment && (index == params[:line_id].to_i)
      hr

      = render 'comments/form'

app/views/codes/_show.slim
- if notice
  .alert.alert-warning.alert-dismissible.fade.show role="alert"
    strong = notice
    button.close type="button" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;
h4
  = @code.title

.row
  .col-auto
    h4
      span.badge.badge-success = @code.author.presence || 'Guest'
      | &nbsp;
      = link_to '+', new_code_path, class: "badge badge-success"

  .col-auto
    h4
      span class=expired_at
        = distance_of_time_in_words @code.expired_at, Time.now

  .col-auto
    h4
      = link_to 'Link', code_path(@code)
hr

span.badge.badge-primary
  = @code.syntax

= render 'codes/formatted_code'

app/views/codes/new.html.slim
h3 Paste code here
.row
  .col-auto
    = render 'form'

app/views/codes/show.html.slim
= render 'show'

app/views/comments/_form.slim
= form_for @comment, url: code_line_comments_path do |f|
  .container
    .col
      .field
        .form-group.row
          .col-sm-5
            = f.text_area :comment, class: "form-control"
      .field
        .form-group.row
          = f.label :author, class: "col-sm-1 col-form-label"
          .col-sm-2
            = f.text_field :author, class: "form-control form-control-sm"
          .col-sm-2
            = f.button 'Add comment', class: "btn btn-dark btn-sm"

app/views/comments/new.slim
.form-group
  = form_for @code do |f|
    - if @comment.errors.any?
        .alert.alert-danger role="alert"
          button type="button" class="close" data-dismiss="alert" aria-label="Close"
            span aria-hidden="true" &times;
          h5 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
          ul
            - @comment.errors.full_messages.each do |message|
              li = message

= render 'codes/show'

app/views/layouts/application.html.slim
doctype html
html
  head
    title LookAtMyCode
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .container
      = yield